# Generated by Django 3.2.9 on 2021-11-19 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('codordemservico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entrada', models.DateField()),
                ('saida', models.DateField()),
                ('total', models.FloatField()),
                ('codcliente', models.IntegerField()),
                ('placa', models.CharField(max_length=7)),
                ('codfuncionario', models.IntegerField()),
                ('pendente', models.CharField(max_length=1)),
                ('totalservico', models.FloatField()),
                ('valordes', models.FloatField()),
            ],
        ),
    ]
