# Generated by Django 3.2.9 on 2021-11-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='valordes',
            new_name='valordesconto',
        ),
    ]
