# Generated by Django 3.2.9 on 2021-11-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_rename_valordes_ordemservico_valordesconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='codordemservico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
