# Generated by Django 3.2.9 on 2021-11-27 03:03

from django.db import migrations, models
import tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_ordemservico_codordemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codcliente', models.BigAutoField(db_column='CODCLIENTE', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
                ('cpfcnpj', models.BigIntegerField(db_column='CPFCNPJ', unique=True)),
                ('rg', models.IntegerField(db_column='RG')),
                ('telefone', models.BigIntegerField(db_column='TELEFONE')),
                ('celular', models.BigIntegerField(db_column='CELULAR')),
                ('codendereco', models.BigIntegerField(db_column='CODENDERECO')),
                ('tipocliente', models.CharField(db_column='TIPOCLIENTE', max_length=100)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteVeiculo',
            fields=[
                ('codigo', models.BigAutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('cpfcnpj', models.BigIntegerField(db_column='CPFCNPJ')),
                ('placa', models.CharField(db_column='PLACA', max_length=7)),
            ],
            options={
                'db_table': 'cliente_veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codempresa', models.BigAutoField(db_column='CODEMPRESA', primary_key=True, serialize=False)),
                ('cnpj', models.BigIntegerField(db_column='CNPJ', unique=True)),
                ('razaosocial', models.CharField(db_column='RAZAOSOCIAL', max_length=255)),
                ('codendereco', models.BigIntegerField(db_column='CODENDERECO')),
                ('logoempresa', models.ImageField(upload_to=tool.models.upload_image_empresa)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('codendereco', models.BigAutoField(db_column='CODENDERECO', primary_key=True, serialize=False)),
                ('rua', models.CharField(db_column='RUA', max_length=255)),
                ('numero', models.IntegerField(db_column='NUMERO')),
                ('bairro', models.CharField(db_column='BAIRRO', max_length=100)),
                ('cidade', models.CharField(db_column='CIDADE', max_length=100)),
                ('estado', models.CharField(db_column='ESTADO', max_length=2)),
                ('cep', models.IntegerField(db_column='CEP')),
                ('latitude', models.FloatField(db_column='LATITUDE')),
                ('longitude', models.FloatField(db_column='LONGITUDE')),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('codfuncionario', models.BigAutoField(db_column='CODFUNCIONARIO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
                ('cpfcnpj', models.BigIntegerField(db_column='CPFCNPJ', unique=True)),
                ('rg', models.IntegerField(db_column='RG')),
                ('telefone', models.BigIntegerField(db_column='TELEFONE')),
                ('dataadmissao', models.DateField(db_column='DATAADMISSAO')),
                ('salario', models.FloatField(db_column='SALARIO')),
                ('especialidade', models.CharField(db_column='ESPECIALIDADE', max_length=100)),
                ('foto', models.ImageField(upload_to=tool.models.upload_image_funcionario)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('coditem', models.BigAutoField(db_column='CODITEM', primary_key=True, serialize=False)),
                ('instrucao', models.CharField(db_column='INSTRUCAO', max_length=255)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nfservico',
            fields=[
                ('codigonf', models.BigAutoField(db_column='CODIGONF', primary_key=True, serialize=False)),
                ('numeronota', models.BigIntegerField(db_column='NUMERONOTA', unique=True)),
                ('datafaturamento', models.DateField(db_column='DATAFATURAMENTO')),
                ('codempresa', models.BigIntegerField(db_column='CODEMPRESA')),
                ('codcliente', models.BigIntegerField(db_column='CODCLIENTE')),
                ('atividade', models.CharField(db_column='ATIVIDADE', max_length=100)),
                ('observacao', models.CharField(db_column='OBSERVACAO', max_length=255)),
                ('codordemservico', models.BigIntegerField(db_column='CODORDEMSERVICO')),
                ('valortotal', models.FloatField(db_column='VALORTOTAL')),
                ('valordesconto', models.FloatField(db_column='VALORDESCONTO')),
                ('tipovenda', models.CharField(db_column='TIPOVENDA', max_length=100)),
            ],
            options={
                'db_table': 'nfservico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordem_Servico',
            fields=[
                ('codigo', models.BigAutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('codordemservico', models.BigIntegerField(db_column='CODORDEMSERVICO')),
                ('codservico', models.BigIntegerField(db_column='CODSERVICO')),
                ('codfuncionario', models.BigIntegerField(db_column='CODFUNCIONARIO')),
            ],
            options={
                'db_table': 'ordem_servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('codservico', models.BigAutoField(db_column='CODSERVICO', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='DESCRICAO', max_length=255)),
                ('preco', models.FloatField(db_column='PRECO')),
            ],
            options={
                'db_table': 'servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicoItem',
            fields=[
                ('codigo', models.BigAutoField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('codservico', models.BigIntegerField(db_column='CODSERVICO')),
                ('coditem', models.BigIntegerField(db_column='CODITEM')),
            ],
            options={
                'db_table': 'servico_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codusuario', models.BigAutoField(db_column='CODUSUARIO', primary_key=True, serialize=False)),
                ('login', models.CharField(db_column='LOGIN', max_length=255)),
                ('senha', models.CharField(db_column='SENHA', max_length=255)),
                ('cadastro', models.DateField(db_column='CADASTRO')),
                ('codfuncionario', models.BigIntegerField(db_column='CODFUNCIONARIO')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(db_column='PLACA', max_length=7, primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='MARCA', max_length=100)),
                ('modelo', models.CharField(db_column='MODELO', max_length=100)),
            ],
            options={
                'db_table': 'veiculo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'managed': False},
        ),
    ]
